### ISSUE TITLE
How to set the signature window display relative to the current line

### ISSUE THREAD

**Issue by wqk151** [erhickey/sig-window-nvim#3]
How to set the signature window display relative to the current line ?

**Comment by erhickey** [comment]
You can override the window_config function, and return a config that has the row and col set to the position of the cursor:

```lua
require('sig-window-nvim').setup({
  window_config = function(label, config, width, height, other_labels)
    local r, c = unpack(vim.api.nvim_win_get_cursor(0))

    return {
      relative = 'editor',
      anchor = 'NE',
      width = width,
      height = height,
      row = r - height - 3,
      col = c,
      focusable = false,
      zindex = config.zindex,
      style = 'minimal',
      border = config.border,
    }
  end
})
```

In this example I subtract the height of the window, and 3 (2 for the borders, and offset the window by 1), from the cursor position to place the window just above the current line.

**Comment by wqk151** [comment]
Thank you, it works well.
